### ISSUE TITLE
Correct placement flow to expose service only when deployment is ready

### ISSUE THREAD

**Issue by mrkisaolamb** [openstack-k8s-operators/placement-operator#188]
On the end of the loop we had
 `	// Only expose the service is the deployment succeeded
	if !instance.Status.Conditions.IsTrue(condition.DeploymentReadyCondition) {
		Log.Info("Waiting for the Deployment to become Ready before exposing the sevice in Keystone")
		return ctrl.Result{}, nil
	}
	`
which doesn't make any sense and mess with correct status order of conditions. So ensureServiceExposed should be moved to correct place and check should be readded

**Comment by gibizer** [comment]
Please be aware that as soon as you add the waiting logic back the unstable test `PlacementAPI controller when The  service is fully running should move the finalizer to a new MariaDBAccount when create is complete` will show up. The reason of that test failure is that the mariadb account rotation test case does not make the deployment ready after the rotation. But the rotation changes the config hash on the deployment and that will bump the generation of the Deployment. So the test needs an additional call to `SimulateDeploymentReplicaReady` after the deployment is updated by the controller. Right now it is not easy to add as the `UpdateAccount` callback runs before the new account is made ready by the mariadb-operator/api code and therefore runs before the deployment is updated.

**Comment by gibizer** [comment]
https://github.com/openstack-k8s-operators/mariadb-operator/blob/9de2d1f1915e965d48534e183e3d55e5e789d610/api/test/helpers/harnesses.go#L286-L287

so we would need the SimulateDeploymentReplicaReady call after 			harness.mariaDBHelper.SimulateMariaDBAccountCompleted(newAccountName) (and after we ensured that the deployment is updated with the new hash) but we don't have a callback for it.
