### ISSUE TITLE
Expose placement-api logs as the pod logs

### ISSUE THREAD

**Issue by gibizer** [openstack-k8s-operators/placement-operator#81]
It seems only the apache logs are exposed at the moment but not the service logs

**Comment by mrkisaolamb** [comment]
After https://github.com/openstack-k8s-operators/placement-operator/commit/ed3136b3444195d82f85662b9fa37e57bd7a80cf landed I can see requestlog in /var/log/placement/placement-api.log so IMO this can be closed
